# Generated by Django 3.2.3 on 2021-05-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0002_issuedbook_studentextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('notavailable', 'Notavailable')], default='available', max_length=30),
        ),
    ]
